services:
  mongodb:
    image: mongo
    container_name: avocat-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    image: localhost:8083/avocat-backend:1.0
    container_name: avocat-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/avocat-pro
      JWT_SECRET: avocat-pro-secret-key-2024-secure
      JWT_EXPIRES_IN: 7d
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "3000:3000"
      
  frontend:
    build: ./frontend
    image: localhost:8083/avocat-frontend:1.0
    container_name: avocat-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
volumes:
  mongo_data:
  uploads_data: